import { Metadata } from "next";

export const metadata: Metadata = {
	title: 'About | NextJS',
	description: 'Generated by create next app',
};


export default function About() {
    return (
        <div>
            <h3>Select subitem</h3>
        </div>
    );
}